CREATE TABLE camaras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL CONSTRAINT uk_camaras_codigo UNIQUE,
    nome VARCHAR(100) NOT NULL,
    unidade VARCHAR(100) NOT NULL,
    capacidade INT NOT NULL CHECK (capacidade > 0),
    temperatura_minima NUMERIC(4,1) NOT NULL,
    temperatura_maxima NUMERIC(4,1) NOT NULL,
    estado VARCHAR(20) NOT NULL CONSTRAINT chk_camaras_estado
        CHECK (estado IN ('OPERACIONAL', 'MANUTENCAO', 'DESATIVADA')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_faixa_termica CHECK (temperatura_minima < temperatura_maxima)
);

CREATE INDEX idx_camaras_unidade_ci ON camaras (lower(unidade));
CREATE INDEX idx_camaras_estado ON camaras (estado);
