CREATE TABLE lotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL CONSTRAINT uk_lotes_codigo UNIQUE,
    imunobiologico VARCHAR(100) NOT NULL,
    fabricante VARCHAR(100) NOT NULL,
    validade DATE NOT NULL,
    quantidade INT NOT NULL CONSTRAINT chk_lotes_quantidade CHECK (quantidade >= 0),
    camara_id BIGINT NOT NULL CONSTRAINT fk_lotes_camara REFERENCES camaras (id),
    estado VARCHAR(20) NOT NULL CONSTRAINT chk_lotes_estado
        CHECK (estado IN ('DISPONIVEL', 'ESGOTADO', 'DESCARTADO')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL,
    -- A baixa total zera a quantidade (ESGOTADO); só o lote disponível precisa ter doses.
    CONSTRAINT chk_lotes_disponivel_com_doses CHECK (estado <> 'DISPONIVEL' OR quantidade > 0),
    CONSTRAINT chk_lotes_esgotado_sem_doses CHECK (estado <> 'ESGOTADO' OR quantidade = 0)
);

CREATE INDEX idx_lotes_camara_id ON lotes (camara_id);
CREATE INDEX idx_lotes_validade ON lotes (validade);
CREATE INDEX idx_lotes_estado ON lotes (estado);
